In [1]:
# -*- coding: utf-8 -*-
"""
Created on Tue May 10 15:08:27 2022

@author: ess
"""

import numpy as np
import matplotlib.pyplot as plt
import numpy.random as rnd

### Create random 4d data

In [2]:
mu = np.array([10,13,7,6])
sigma = np.array([[12.61, 11.51, 11.52, 11.32], [11.51, 12.44, 11.36, 11.33], [11.52, 11.36, 12.83, 11.34],
                  [11.32, 11.33, 11.34, 12.27]])
y = np.linspace(1, 100, num = 1000)
print("Mu ", mu.shape)
print("Sigma ", sigma.shape)

Mu  (4,)
Sigma  (4, 4)


### Create 1000 samples using mean and sigma

In [3]:
org_data = rnd.multivariate_normal(mu, sigma, size=(1000))
print("Data shape ", org_data.shape)

Data shape  (1000, 4)


### Subtract mean from data

In [4]:
mean = np.mean(org_data, axis= 0)
print("Mean ", mean.shape)
mean_data = org_data - mean
print("Data after subtracting mean ", org_data.shape, "\n")

Mean  (4,)
Data after subtracting mean  (1000, 4) 



### Compute covariance matrix

In [5]:
cov = np.cov(mean_data.T)
cov = np.round(cov, 2)
print("Covariance matrix ", cov.shape, "\n")

Covariance matrix  (4, 4) 



### Perform eigen decomposition of covariance matrix

In [6]:
eig_val, eig_vec = np.linalg.eig(cov)
print("Eigen vectors ", eig_vec)
print("Eigen values ", eig_val, "\n")

Eigen vectors  [[ 0.50858694  0.32729825  0.7370175   0.30169584]
 [ 0.49583054  0.40784032 -0.22299342 -0.73354774]
 [ 0.50817455 -0.84344507  0.08593536 -0.15157223]
 [ 0.48708318  0.12305501 -0.63221377  0.58984167]]
Eigen values  [42.63099174  1.38039599  1.03254741  0.92606486] 



### Sort eigen values and corresponding eigen vectors in descending order

In [7]:
indices = np.arange(0,len(eig_val), 1)
indices = ([x for _,x in sorted(zip(eig_val, indices))])[::-1]
eig_val = eig_val[indices]
eig_vec = eig_vec[:,indices]
print("Sorted Eigen vectors ", eig_vec)
print("Sorted Eigen values ", eig_val, "\n")

Sorted Eigen vectors  [[ 0.50858694  0.32729825  0.7370175   0.30169584]
 [ 0.49583054  0.40784032 -0.22299342 -0.73354774]
 [ 0.50817455 -0.84344507  0.08593536 -0.15157223]
 [ 0.48708318  0.12305501 -0.63221377  0.58984167]]
Sorted Eigen values  [42.63099174  1.38039599  1.03254741  0.92606486] 



### Get explained variance

In [8]:
sum_eig_val = np.sum(eig_val)
explained_variance = eig_val/ sum_eig_val
print(explained_variance)
cumulative_variance = np.cumsum(explained_variance)
print(cumulative_variance)

[0.92736549 0.03002819 0.02246133 0.02014498]
[0.92736549 0.95739369 0.97985502 1.        ]


### Take transpose of eigen vectors with data

In [9]:
pca_data = np.dot(mean_data, eig_vec)
print("Transformed data ", pca_data.shape)

Transformed data  (1000, 4)


In [10]:
mpg = datasets.load_iris()

NameError: name 'datasets' is not defined

reference : https://towardsdatascience.com/a-step-by-step-implementation-of-principal-component-analysis-5520cc6cd598